"""add status field on call model & add user_id field on session model

Revision ID: 579dc7380340
Revises: 9385b1c86dd7
Create Date: 2025-12-24 14:58:56.783849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '579dc7380340'
down_revision: Union[str, Sequence[str], None] = '9385b1c86dd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('status', sa.String(), nullable=True))
    op.add_column('sessions', sa.Column('user_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'user_id')
    op.drop_column('calls', 'status')
    # ### end Alembic commands ###
