"""change nullable=False for field status and user_id

Revision ID: 6336fddabaac
Revises: 579dc7380340
Create Date: 2025-12-24 15:10:31.100309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6336fddabaac'
down_revision: Union[str, Sequence[str], None] = '579dc7380340'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calls', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('sessions', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('calls', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
